# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cplexWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cplexWindow(object):
    def setupUi(self, cplexWindow):
        cplexWindow.setObjectName("cplexWindow")
        cplexWindow.resize(699, 554)
        self.centralwidget = QtWidgets.QWidget(cplexWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(520, 520, 168, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_10.addWidget(self.cancelButton)
        self.runButton = QtWidgets.QPushButton(self.layoutWidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_10.addWidget(self.runButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 681, 504))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_29.setObjectName("label_29")
        self.verticalLayout.addWidget(self.label_29, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stateLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.stateLabel.setObjectName("stateLabel")
        self.horizontalLayout.addWidget(self.stateLabel)
        self.stateInput = QtWidgets.QComboBox(self.layoutWidget1)
        self.stateInput.setObjectName("stateInput")
        self.horizontalLayout.addWidget(self.stateInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.labelCities = QtWidgets.QLabel(self.layoutWidget1)
        self.labelCities.setText("")
        self.labelCities.setObjectName("labelCities")
        self.horizontalLayout_11.addWidget(self.labelCities)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.labelMinPop = QtWidgets.QLabel(self.layoutWidget1)
        self.labelMinPop.setText("")
        self.labelMinPop.setObjectName("labelMinPop")
        self.horizontalLayout_11.addWidget(self.labelMinPop)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.labelMaxPop = QtWidgets.QLabel(self.layoutWidget1)
        self.labelMaxPop.setText("")
        self.labelMaxPop.setObjectName("labelMaxPop")
        self.horizontalLayout_11.addWidget(self.labelMaxPop)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setMaximumSize(QtCore.QSize(50, 30))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.inputSupplyPopMin = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputSupplyPopMin.setMaximumSize(QtCore.QSize(206, 30))
        self.inputSupplyPopMin.setObjectName("inputSupplyPopMin")
        self.horizontalLayout_12.addWidget(self.inputSupplyPopMin)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setMaximumSize(QtCore.QSize(30, 30))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.inputSupplyPopMax = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputSupplyPopMax.setMaximumSize(QtCore.QSize(206, 30))
        self.inputSupplyPopMax.setObjectName("inputSupplyPopMax")
        self.horizontalLayout_12.addWidget(self.inputSupplyPopMax)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_13.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setMaximumSize(QtCore.QSize(50, 30))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.inputFacilityPopMin = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputFacilityPopMin.setMaximumSize(QtCore.QSize(206, 29))
        self.inputFacilityPopMin.setObjectName("inputFacilityPopMin")
        self.horizontalLayout_13.addWidget(self.inputFacilityPopMin)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_20.setMaximumSize(QtCore.QSize(30, 30))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.inputFacilityPopMax = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputFacilityPopMax.setMaximumSize(QtCore.QSize(206, 30))
        self.inputFacilityPopMax.setObjectName("inputFacilityPopMax")
        self.horizontalLayout_13.addWidget(self.inputFacilityPopMax)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_21.setMaximumSize(QtCore.QSize(50, 30))
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.inputDemandPopMin = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputDemandPopMin.setMaximumSize(QtCore.QSize(206, 29))
        self.inputDemandPopMin.setObjectName("inputDemandPopMin")
        self.horizontalLayout_14.addWidget(self.inputDemandPopMin)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_26.setMaximumSize(QtCore.QSize(30, 30))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_14.addWidget(self.label_26)
        self.inputDemandPopMax = QtWidgets.QLineEdit(self.layoutWidget1)
        self.inputDemandPopMax.setMaximumSize(QtCore.QSize(206, 29))
        self.inputDemandPopMax.setObjectName("inputDemandPopMax")
        self.horizontalLayout_14.addWidget(self.inputDemandPopMax)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_27.setObjectName("label_27")
        self.verticalLayout.addWidget(self.label_27, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fixed_cost1 = QtWidgets.QLabel(self.layoutWidget1)
        self.fixed_cost1.setObjectName("fixed_cost1")
        self.horizontalLayout_2.addWidget(self.fixed_cost1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_10.setMaximumSize(QtCore.QSize(50, 30))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.input_f_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_f_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_f_min.setInputMask("")
        self.input_f_min.setPlaceholderText("")
        self.input_f_min.setObjectName("input_f_min")
        self.horizontalLayout_2.addWidget(self.input_f_min)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_11.setMaximumSize(QtCore.QSize(30, 30))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.input_f_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_f_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_f_max.setObjectName("input_f_max")
        self.horizontalLayout_2.addWidget(self.input_f_max)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.numbernode2 = QtWidgets.QLabel(self.layoutWidget1)
        self.numbernode2.setObjectName("numbernode2")
        self.horizontalLayout_9.addWidget(self.numbernode2)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_24.setMaximumSize(QtCore.QSize(50, 30))
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_9.addWidget(self.label_24)
        self.input_fm_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_fm_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_fm_min.setObjectName("input_fm_min")
        self.horizontalLayout_9.addWidget(self.input_fm_min)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_25.setMaximumSize(QtCore.QSize(30, 30))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.input_fm_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_fm_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_fm_max.setObjectName("input_fm_max")
        self.horizontalLayout_9.addWidget(self.input_fm_max)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fixed_cost2 = QtWidgets.QLabel(self.layoutWidget1)
        self.fixed_cost2.setObjectName("fixed_cost2")
        self.horizontalLayout_3.addWidget(self.fixed_cost2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setMaximumSize(QtCore.QSize(50, 30))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.input_c0_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_c0_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_c0_min.setObjectName("input_c0_min")
        self.horizontalLayout_3.addWidget(self.input_c0_min)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setMaximumSize(QtCore.QSize(30, 30))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        self.input_c0_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_c0_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_c0_max.setObjectName("input_c0_max")
        self.horizontalLayout_3.addWidget(self.input_c0_max)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.numbernode1 = QtWidgets.QLabel(self.layoutWidget1)
        self.numbernode1.setObjectName("numbernode1")
        self.horizontalLayout_8.addWidget(self.numbernode1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_22.setMaximumSize(QtCore.QSize(50, 30))
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_8.addWidget(self.label_22)
        self.input_cr_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_cr_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_cr_min.setObjectName("input_cr_min")
        self.horizontalLayout_8.addWidget(self.input_cr_min)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_23.setMaximumSize(QtCore.QSize(30, 30))
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_8.addWidget(self.label_23)
        self.input_cr_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_cr_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_cr_max.setObjectName("input_cr_max")
        self.horizontalLayout_8.addWidget(self.input_cr_max)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_28.setObjectName("label_28")
        self.verticalLayout.addWidget(self.label_28, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.capacity1 = QtWidgets.QLabel(self.layoutWidget1)
        self.capacity1.setObjectName("capacity1")
        self.horizontalLayout_4.addWidget(self.capacity1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setMaximumSize(QtCore.QSize(50, 30))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.input_a_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_a_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_a_min.setObjectName("input_a_min")
        self.horizontalLayout_4.addWidget(self.input_a_min)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setMaximumSize(QtCore.QSize(30, 30))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_4.addWidget(self.label_15)
        self.input_a_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_a_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_a_max.setObjectName("input_a_max")
        self.horizontalLayout_4.addWidget(self.input_a_max)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.capacity2 = QtWidgets.QLabel(self.layoutWidget1)
        self.capacity2.setObjectName("capacity2")
        self.horizontalLayout_5.addWidget(self.capacity2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setMaximumSize(QtCore.QSize(50, 30))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.input_b_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_b_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_b_min.setObjectName("input_b_min")
        self.horizontalLayout_5.addWidget(self.input_b_min)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_17.setMaximumSize(QtCore.QSize(30, 30))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.input_b_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_b_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_b_max.setObjectName("input_b_max")
        self.horizontalLayout_5.addWidget(self.input_b_max)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.demand = QtWidgets.QLabel(self.layoutWidget1)
        self.demand.setObjectName("demand")
        self.horizontalLayout_6.addWidget(self.demand)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_18.setMaximumSize(QtCore.QSize(50, 30))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_6.addWidget(self.label_18)
        self.input_m_min = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_m_min.setMaximumSize(QtCore.QSize(206, 29))
        self.input_m_min.setObjectName("input_m_min")
        self.horizontalLayout_6.addWidget(self.input_m_min)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_19.setMaximumSize(QtCore.QSize(30, 30))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_6.addWidget(self.label_19)
        self.input_m_max = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_m_max.setMaximumSize(QtCore.QSize(206, 29))
        self.input_m_max.setObjectName("input_m_max")
        self.horizontalLayout_6.addWidget(self.input_m_max)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        cplexWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(cplexWindow)
        QtCore.QMetaObject.connectSlotsByName(cplexWindow)

    def retranslateUi(self, cplexWindow):
        _translate = QtCore.QCoreApplication.translate
        cplexWindow.setWindowTitle(_translate("cplexWindow", "MainWindow"))
        self.cancelButton.setText(_translate("cplexWindow", "CANCEL"))
        self.runButton.setText(_translate("cplexWindow", "RUN"))
        self.label_29.setText(_translate("cplexWindow", "Localização dos Pontos e Faixas de Habitantes"))
        self.stateLabel.setText(_translate("cplexWindow", "Estado:"))
        self.label_3.setText(_translate("cplexWindow", "# Cidades:"))
        self.label_2.setText(_translate("cplexWindow", "População Mínima:"))
        self.label.setText(_translate("cplexWindow", "População Máxima:"))
        self.label_4.setText(_translate("cplexWindow", "População Cliente: "))
        self.label_7.setText(_translate("cplexWindow", "de"))
        self.label_8.setText(_translate("cplexWindow", "a"))
        self.label_5.setText(_translate("cplexWindow", "População Facilidade:"))
        self.label_9.setText(_translate("cplexWindow", "de"))
        self.label_20.setText(_translate("cplexWindow", "a"))
        self.label_6.setText(_translate("cplexWindow", "População Demanda:"))
        self.label_21.setText(_translate("cplexWindow", "de"))
        self.label_26.setText(_translate("cplexWindow", "a"))
        self.label_27.setText(_translate("cplexWindow", "Custos de Instalação, Reprocessamento e Transporte"))
        self.fixed_cost1.setText(_translate("cplexWindow", "Instalação de Facilidade (f):"))
        self.label_10.setText(_translate("cplexWindow", "de R$"))
        self.label_11.setText(_translate("cplexWindow", "a R$"))
        self.numbernode2.setText(_translate("cplexWindow", "Reprocessamento (fm):"))
        self.label_24.setText(_translate("cplexWindow", "de R$"))
        self.label_25.setText(_translate("cplexWindow", "a R$"))
        self.fixed_cost2.setText(_translate("cplexWindow", "Transporte Fornecedor (c0):"))
        self.label_12.setText(_translate("cplexWindow", "de R$"))
        self.label_13.setText(_translate("cplexWindow", "a R$"))
        self.numbernode1.setText(_translate("cplexWindow", "Transporte Demanda (cr):"))
        self.label_22.setText(_translate("cplexWindow", "de R$"))
        self.label_23.setText(_translate("cplexWindow", "a R$"))
        self.label_28.setText(_translate("cplexWindow", "Capacidade de Fornecimento , Reprocessamento e Demanda"))
        self.capacity1.setText(_translate("cplexWindow", "Fornecimento (a):"))
        self.label_14.setText(_translate("cplexWindow", "de"))
        self.label_15.setText(_translate("cplexWindow", "a"))
        self.capacity2.setText(_translate("cplexWindow", "Demanda (b):"))
        self.label_16.setText(_translate("cplexWindow", "de"))
        self.label_17.setText(_translate("cplexWindow", "a"))
        self.demand.setText(_translate("cplexWindow", "Reprocessamento (m):"))
        self.label_18.setText(_translate("cplexWindow", "de"))
        self.label_19.setText(_translate("cplexWindow", "a"))

