# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_solutionWindow(object):
    def setupUi(self, solutionWindow):
        solutionWindow.setObjectName("solutionWindow")
        solutionWindow.resize(632, 517)
        self.verticalLayoutWidget = QtWidgets.QWidget(solutionWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 611, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.labelStateName = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelStateName.setText("")
        self.labelStateName.setObjectName("labelStateName")
        self.horizontalLayout_6.addWidget(self.labelStateName)
        self.labelSupplyPoints = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelSupplyPoints.setObjectName("labelSupplyPoints")
        self.horizontalLayout_6.addWidget(self.labelSupplyPoints)
        self.labelSupplyPointsCount = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelSupplyPointsCount.setMaximumSize(QtCore.QSize(40, 30))
        self.labelSupplyPointsCount.setText("")
        self.labelSupplyPointsCount.setObjectName("labelSupplyPointsCount")
        self.horizontalLayout_6.addWidget(self.labelSupplyPointsCount)
        self.labelFacilities = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelFacilities.setObjectName("labelFacilities")
        self.horizontalLayout_6.addWidget(self.labelFacilities)
        self.labelFacilitiesCount = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelFacilitiesCount.setMaximumSize(QtCore.QSize(40, 30))
        self.labelFacilitiesCount.setText("")
        self.labelFacilitiesCount.setObjectName("labelFacilitiesCount")
        self.horizontalLayout_6.addWidget(self.labelFacilitiesCount)
        self.labelDemandPoints = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelDemandPoints.setObjectName("labelDemandPoints")
        self.horizontalLayout_6.addWidget(self.labelDemandPoints)
        self.labelDemandPointsCount = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelDemandPointsCount.setMaximumSize(QtCore.QSize(40, 30))
        self.labelDemandPointsCount.setText("")
        self.labelDemandPointsCount.setObjectName("labelDemandPointsCount")
        self.horizontalLayout_6.addWidget(self.labelDemandPointsCount)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.labelTotalFacilitiesCost = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTotalFacilitiesCost.setMaximumSize(QtCore.QSize(250, 30))
        self.labelTotalFacilitiesCost.setText("")
        self.labelTotalFacilitiesCost.setObjectName("labelTotalFacilitiesCost")
        self.horizontalLayout.addWidget(self.labelTotalFacilitiesCost)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(500, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.labelTotalProductsCost = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTotalProductsCost.setMaximumSize(QtCore.QSize(250, 30))
        self.labelTotalProductsCost.setText("")
        self.labelTotalProductsCost.setObjectName("labelTotalProductsCost")
        self.horizontalLayout_2.addWidget(self.labelTotalProductsCost)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.labelTotalUnitsOverflow = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTotalUnitsOverflow.setMaximumSize(QtCore.QSize(250, 30))
        self.labelTotalUnitsOverflow.setText("")
        self.labelTotalUnitsOverflow.setObjectName("labelTotalUnitsOverflow")
        self.horizontalLayout_3.addWidget(self.labelTotalUnitsOverflow)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.labelTotalOverflowCost = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTotalOverflowCost.setMaximumSize(QtCore.QSize(250, 30))
        self.labelTotalOverflowCost.setText("")
        self.labelTotalOverflowCost.setObjectName("labelTotalOverflowCost")
        self.horizontalLayout_4.addWidget(self.labelTotalOverflowCost)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.labelTotalCost = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTotalCost.setMaximumSize(QtCore.QSize(250, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelTotalCost.setFont(font)
        self.labelTotalCost.setText("")
        self.labelTotalCost.setObjectName("labelTotalCost")
        self.horizontalLayout_5.addWidget(self.labelTotalCost)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.exitButton = QtWidgets.QPushButton(solutionWindow)
        self.exitButton.setGeometry(QtCore.QRect(290, 480, 60, 25))
        self.exitButton.setMaximumSize(QtCore.QSize(60, 25))
        self.exitButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(solutionWindow)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 210, 611, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.layoutMap = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.layoutMap.setContentsMargins(0, 0, 0, 0)
        self.layoutMap.setObjectName("layoutMap")

        self.retranslateUi(solutionWindow)
        QtCore.QMetaObject.connectSlotsByName(solutionWindow)

    def retranslateUi(self, solutionWindow):
        _translate = QtCore.QCoreApplication.translate
        solutionWindow.setWindowTitle(_translate("solutionWindow", "Solução"))
        self.label_11.setText(_translate("solutionWindow", "Estado:"))
        self.labelSupplyPoints.setText(_translate("solutionWindow", "Fornecedores:"))
        self.labelFacilities.setText(_translate("solutionWindow", "Facilidades:"))
        self.labelDemandPoints.setText(_translate("solutionWindow", "Pontos de Demanda:"))
        self.label.setText(_translate("solutionWindow", "Custo Total das Facilidades: "))
        self.label_3.setText(_translate("solutionWindow", "Custo Total de Reprocessamento e Transporte dos Produtos: "))
        self.label_4.setText(_translate("solutionWindow", "Total de Unidades em Excesso:"))
        self.label_5.setText(_translate("solutionWindow", "Custo Total de Unidades em Excesso:"))
        self.label_6.setText(_translate("solutionWindow", "Custo Total:"))
        self.exitButton.setText(_translate("solutionWindow", "Fechar"))

