# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'solutionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_solutionWindow(object):
    def setupUi(self, solutionWindow):
        solutionWindow.setObjectName("solutionWindow")
        solutionWindow.resize(695, 478)
        self.centralwidget = QtWidgets.QWidget(solutionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 651, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.costResult = QtWidgets.QTextBrowser(self.layoutWidget)
        self.costResult.setMaximumSize(QtCore.QSize(206, 29))
        self.costResult.setObjectName("costResult")
        self.horizontalLayout.addWidget(self.costResult)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.demandResult = QtWidgets.QTextBrowser(self.layoutWidget)
        self.demandResult.setMaximumSize(QtCore.QSize(206, 29))
        self.demandResult.setObjectName("demandResult")
        self.horizontalLayout_2.addWidget(self.demandResult)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.trasportCost = QtWidgets.QTextBrowser(self.layoutWidget)
        self.trasportCost.setMaximumSize(QtCore.QSize(206, 29))
        self.trasportCost.setObjectName("trasportCost")
        self.horizontalLayout_3.addWidget(self.trasportCost)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.mediumTransportCost = QtWidgets.QTextBrowser(self.layoutWidget)
        self.mediumTransportCost.setMaximumSize(QtCore.QSize(206, 29))
        self.mediumTransportCost.setObjectName("mediumTransportCost")
        self.horizontalLayout_4.addWidget(self.mediumTransportCost)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.others = QtWidgets.QTextBrowser(self.layoutWidget)
        self.others.setMaximumSize(QtCore.QSize(206, 29))
        self.others.setObjectName("others")
        self.horizontalLayout_5.addWidget(self.others)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.graphicsView = QtWidgets.QGraphicsView(self.layoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(500, 400, 168, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.saveLabel = QtWidgets.QPushButton(self.layoutWidget1)
        self.saveLabel.setObjectName("saveLabel")
        self.horizontalLayout_6.addWidget(self.saveLabel)
        self.exitButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout_6.addWidget(self.exitButton)
        solutionWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(solutionWindow)
        QtCore.QMetaObject.connectSlotsByName(solutionWindow)

    def retranslateUi(self, solutionWindow):
        _translate = QtCore.QCoreApplication.translate
        solutionWindow.setWindowTitle(_translate("solutionWindow", "MainWindow"))
        self.label_5.setText(_translate("solutionWindow", "Custo:"))
        self.label_6.setText(_translate("solutionWindow", "$"))
        self.label_4.setText(_translate("solutionWindow", "Demanda média:"))
        self.label.setText(_translate("solutionWindow", "Custo de Transporte:"))
        self.label_8.setText(_translate("solutionWindow", "$"))
        self.label_2.setText(_translate("solutionWindow", "Custo de Transporte Médio:"))
        self.label_9.setText(_translate("solutionWindow", "$"))
        self.label_3.setText(_translate("solutionWindow", "Outros:"))
        self.saveLabel.setText(_translate("solutionWindow", "SAVE"))
        self.exitButton.setText(_translate("solutionWindow", "EXIT"))

